[2025-06-13T03:40:20.683+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-13T03:40:20.703+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:38:00+00:00 [queued]>
[2025-06-13T03:40:20.712+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:38:00+00:00 [queued]>
[2025-06-13T03:40:20.713+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-06-13T03:40:20.726+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): cash_processing_task> on 2025-06-13 03:38:00+00:00
[2025-06-13T03:40:20.732+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-13T03:40:20.734+0000] {standard_task_runner.py:72} INFO - Started process 135 to run task
[2025-06-13T03:40:20.734+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'payparser_pipeline_dag', 'cash_processing_task', 'scheduled__2025-06-13T03:38:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/payparser_dag.py', '--cfg-path', '/tmp/tmpdojh_6_s']
[2025-06-13T03:40:20.738+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask cash_processing_task
[2025-06-13T03:40:20.799+0000] {task_command.py:467} INFO - Running <TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:38:00+00:00 [running]> on host 99fad00d6fef
[2025-06-13T03:40:20.887+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zain' AIRFLOW_CTX_DAG_ID='payparser_pipeline_dag' AIRFLOW_CTX_TASK_ID='cash_processing_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T03:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T03:38:00+00:00'
[2025-06-13T03:40:20.889+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-13T03:40:20.907+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/payparser_dag.py", line 143, in process_cash
    insert_transaction(**tx)
TypeError: insert_transaction() got an unexpected keyword argument 'filename'
[2025-06-13T03:40:20.918+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=payparser_pipeline_dag, task_id=cash_processing_task, run_id=scheduled__2025-06-13T03:38:00+00:00, execution_date=20250613T033800, start_date=20250613T034020, end_date=20250613T034020
[2025-06-13T03:40:20.943+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-13T03:40:20.944+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 106 for task cash_processing_task (insert_transaction() got an unexpected keyword argument 'filename'; 135)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/payparser_dag.py", line 143, in process_cash
    insert_transaction(**tx)
TypeError: insert_transaction() got an unexpected keyword argument 'filename'
[2025-06-13T03:40:20.993+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-13T03:40:21.008+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-13T03:40:21.011+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
